### ISSUE TITLE
Linux crash on content close

### ISSUE THREAD

**Issue by realnc** [libretro/bsnes-libretro#15]
When closing content, I get a segfault.

The backtrace doesn't seem very helpful though. It doesn't contain anything from bsnes itself, only from RetroArch:

```
Thread 4 "retroarch-debug" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc7bff640 (LWP 17838)]
0x00007ffff11f474c in ?? ()

Thread 20 (Thread 0x7ffff0a47640 (LWP 17854) "retroarch-debug"):
#0  0x00007ffff7a916c2 in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x55555846ce3c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007ffff7a9172b in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555846ce3c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007ffff7a8aebf in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555c7b1310, cond=0x55555846ce10) at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x55555846ce10, mutex=0x55555c7b1310) at pthread_cond_wait.c:619
#4  0x000055555593c76e in scond_wait (cond=0x55555846ce10, lock=0x55555c7b1310) at libretro-common/rthreads/rthreads.c:733
#5  0x0000555555637a43 in threaded_worker (userdata=0x0) at libretro-common/queues/task_queue.c:489
#6  0x000055555593c33f in thread_wrap (data_=0x555558e80130) at libretro-common/rthreads/rthreads.c:143
#7  0x00007ffff7a84e1e in start_thread (arg=0x7ffff0a47640) at pthread_create.c:481
#8  0x00007ffff5a699cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff121bd80 (LWP 17800) "retroarch-debug"):
#0  0x00007ffff5a5ecff in __GI___poll (fds=0x7fffffff8648, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff78dbd62 in  () at /usr/lib64/libxcb.so.1
#2  0x00007ffff78dde6f in  () at /usr/lib64/libxcb.so.1
#3  0x00007ffff78ddfe2 in xcb_wait_for_reply64 () at /usr/lib64/libxcb.so.1
#4  0x00007ffff79782ec in _XReply () at /usr/lib64/libX11.so.6
#5  0x00007ffff790894d in  () at /usr/lib64/libXrandr.so.2
#6  0x00005555559494c4 in x11_display_server_get_screen_orientation (data=0x5555573f2280) at gfx/display_servers/dispserv_x11.c:413
#7  0x000055555566ece9 in video_display_server_get_screen_orientation () at gfx/video_driver.c:1249
#8  0x000055555566e413 in video_display_server_init (type=RARCH_DISPLAY_X11) at gfx/video_driver.c:1048
#9  0x00005555556740aa in video_driver_init_internal (video_is_threaded=0x7fffffff8b4a, verbosity_enabled=true) at gfx/video_driver.c:3541
#10 0x000055555561d1a7 in drivers_init (settings=0x5555565caa40, flags=2047, verbosity_enabled=true) at driver.c:479
#11 0x0000555555608f3f in retroarch_main_init (argc=9, argv=0x7fffffff8f70) at retroarch.c:5276
#12 0x000055555563b487 in content_load (info=0x7fffffff9500, p_content=0x5555564777d8 <runloop_state+1912>) at tasks/task_content.c:1482
#13 0x000055555563c1b8 in task_push_start_dummy_core (content_info=0x7fffffff9500) at tasks/task_content.c:1867
#14 0x0000555555601124 in command_event (cmd=CMD_EVENT_UNLOAD_CORE, data=0x0) at retroarch.c:1935
#15 0x00005555558ba1f1 in generic_action_ok_command (cmd=CMD_EVENT_UNLOAD_CORE) at menu/cbs/menu_cbs_ok.c:1852
#16 0x00005555558c1ea2 in action_ok_close_content (path=0x7fffffffc878 "Close Content", label=0x7fffffffc977 "unload_core", type=150, idx=2, entry_idx=0) at menu/cbs/menu_cbs_ok.c:5138
#17 0x00005555558b6123 in generic_menu_entry_action (userdata=0x55555847fc90, entry=0x7fffffffc860, i=2, action=MENU_ACTION_OK) at menu/menu_driver.c:7891
#18 0x000055555584e110 in ozone_menu_entry_action (userdata=0x55555847fc90, entry=0x7fffffffc860, i=2, action=MENU_ACTION_OK) at menu/drivers/ozone.c:7019
#19 0x00005555558aed78 in menu_entry_action (entry=0x7fffffffc860, i=2, action=MENU_ACTION_OK) at menu/menu_driver.c:4345
#20 0x00005555558b5752 in generic_menu_iterate (menu_st=0x55555654b840 <menu_driver_state>, p_disp=0x5555564f7480 <dispgfx_st>, p_anim=0x5555564f75a0 <anim_st>, settings=0x5555565caa40, menu=0x5555584193f0, userdata=0x55555847fc90, action=MENU_ACTION_OK, current_time=7108584244) at menu/menu_driver.c:7686
#21 0x00005555558b68bc in menu_driver_iterate (menu_st=0x55555654b840 <menu_driver_state>, p_disp=0x5555564f7480 <dispgfx_st>, p_anim=0x5555564f75a0 <anim_st>, settings=0x5555565caa40, action=MENU_ACTION_OK, current_time=7108584244) at menu/menu_driver.c:8049
#22 0x00005555556180e2 in runloop_check_state (error_on_init=false, settings=0x5555565caa40, current_time=7108584244) at runloop.c:6678
#23 0x000055555561a301 in runloop_iterate () at runloop.c:7458
#24 0x0000555555604834 in rarch_main (argc=4, argv=0x7fffffffd8a8, data=0x0) at retroarch.c:3827
#25 0x0000555555604896 in main (argc=4, argv=0x7fffffffd8a8) at retroarch.c:3908
```

**Comment by realnc** [comment]
Correction: There is not crash when exiting RA. It only crashes with "Close Content."

**Comment by carmiker** [comment]
Seems to no longer be a problem.
